export const heroSlides = [
  {
    id: 'beautiful-spaces',
    eyebrow: 'Beautiful Spaces',
    heading: 'Furniture for a kinder tomorrow',
    description: 'Timeless designs, sustainable materials and everyday comfort — made for a more beautiful home.',
    ctaLabel: 'Shop now',
    ctaHref: '/shop',
    image: '/hero-living-room.png',
    alt: 'Warm contemporary living room with a cream sofa, natural wood table, and leafy plants',
    position: 'center center',
  },
  {
    id: 'quiet-living',
    eyebrow: 'Quiet Living',
    heading: 'Comfort shaped for everyday life',
    description: 'Soft forms, natural textures and considered details for rooms that feel effortlessly complete.',
    ctaLabel: 'Shop now',
    ctaHref: '/shop',
    image: '/hero-lounge.png',
    alt: 'Serene neutral lounge with a woven chair, pale oak furniture, and ceramic decor',
    position: 'center center',
  },
  {
    id: 'timeless-comfort',
    eyebrow: 'Timeless Comfort',
    heading: 'Built for coming together',
    description: 'Warm materials and lasting craftsmanship create an inviting place for every shared moment.',
    ctaLabel: 'Shop now',
    ctaHref: '/shop',
    image: '/hero-dining.png',
    alt: 'Warm cream dining room with a rounded oak table and softly upholstered chairs',
    position: 'center center',
  },
];
